apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: kafka-pvc
  namespace: distributed-url-shortener

  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: distributed-url-shortener

spec:

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi