apiVersion: v1
kind: Secret

metadata:
  name: distributed-url-shortener-secret
  namespace: distributed-url-shortener

  labels:
    app.kubernetes.io/name: distributed-url-shortener
    app.kubernetes.io/part-of: distributed-url-shortener
    app.kubernetes.io/managed-by: kubectl

type: Opaque

stringData:

  POSTGRES_USER: postgres

  POSTGRES_PASSWORD: yash8252

  JWT_SECRET: ThisIsMyVeryLongSecretKeyForDistributedUrlShortenerApplication123456789

  SPRING_PROFILES_ACTIVE: docker