apiVersion: v1
kind: Service

metadata:
  name: redirect-service
  namespace: distributed-url-shortener

  labels:
    app: redirect-service
    app.kubernetes.io/name: redirect-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: distributed-url-shortener

spec:

  selector:
    app: redirect-service

  ports:

    - name: http
      port: 8093
      targetPort: 8093

  type: ClusterIP