apiVersion: v1
kind: Service

metadata:
  name: kafka
  namespace: distributed-url-shortener

  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: distributed-url-shortener

spec:

  selector:
    app: kafka

  ports:

    - name: kafka
      port: 9092
      targetPort: 9092

  type: ClusterIP