########################################################
# Application
########################################################

spring.application.name=discovery-server

server.port=8761


eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always


management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://jaeger:4318/v1/traces

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]