apiVersion: apps/v1
kind: Deployment

metadata:
  name: jaeger
  namespace: distributed-url-shortener

  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: distributed-url-shortener

spec:

  replicas: 1

  selector:
    matchLabels:
      app: jaeger

  template:

    metadata:

      labels:
        app: jaeger

    spec:

      containers:

        - name: jaeger

          image: jaegertracing/all-in-one:latest

          imagePullPolicy: IfNotPresent

          ports:

            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318

          resources:

            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 512Mi

          readinessProbe:

            httpGet:
              path: /
              port: 16686

            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:

            httpGet:
              path: /
              port: 16686

            initialDelaySeconds: 30
            periodSeconds: 20