apiVersion: v1
kind: Service

metadata:
  name: url-service
  namespace: distributed-url-shortener

  labels:
    app: url-service
    app.kubernetes.io/name: url-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: distributed-url-shortener

spec:

  selector:
    app: url-service

  ports:

    - name: http
      port: 8083
      targetPort: 8083

  type: ClusterIP