spring.application.name=redirect-service

server.port=${SERVER_PORT:8092}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/url_service_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:yash8252}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2s

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true

logging.level.root=INFO
logging.level.com.yashdotdev.redirect_service=DEBUG
logging.level.org.springframework.kafka=INFO
logging.level.org.springframework.data.redis=INFO

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

spring.jackson.default-property-inclusion=non_null

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

# Uncomment while debugging
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.orm.jdbc.bind=TRACE