
spring.application.name=redirect-service

server.port=8094


spring.datasource.url=jdbc:postgresql://localhost:5432/redirect_db
spring.datasource.username=postgres
spring.datasource.password=yash8252

spring.jpo.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.jpa.hibernate.format_sql=true


eureka.client.register-with-eureka=true
eureka.client.refresh.enable=false

eureka.client.service_url.defauktZone = true




