apiVersion: v1
kind: Service

metadata:

  name: auth-service
  namespace: distributed-url-shortener

  labels:
    app: auth-service
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: distributed-url-shortener

spec:

  selector:
    app: auth-service

  ports:

    - port: 8082
      targetPort: 8091
      protocol: TCP

  type: ClusterIP