spring.application.name=analytic-service

server.port=8094


spring.datasource.url=jdbc:postgresql://localhost:5432/analytics_service_db
spring.datasource.username=postgres
spring.datasource.password=yash8252

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true


eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.yashdotdev.common.events
spring.kafka.consumer.properties.spring.json.value.default.type=com.yashdotdev.common.events.ClickEvents


management.endpoints.web.exposure.include=*

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
