apiVersion: v1
kind: Service

metadata:
  name: postgres
  namespace: distributed-url-shortener

  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: distributed-url-shortener

spec:

  selector:
    app: postgres

  ports:

    - name: postgres

      port: 5432

      targetPort: 5432

  type: ClusterIP