spring.application.name=url-service
server.port=8092

spring.datasource.url=jdbc:postgresql://postgres:5432/url_service_db
spring.datasource.username=postgres
spring.datasource.password=yash8252
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true


management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://jaeger:4318/v1/traces

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.level.root=INFO
logging.level.com.yashdotdev.url_service=DEBUG


spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

spring.jackson.default-property-inclusion=non_null


server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false