CREATE TABLE url_analytics
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    short_code      VARCHAR(12)                             NOT NULL,
    total_clicks    BIGINT,
    unique_clicks   BIGINT,
    last_clicked_at TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_urlanalytics PRIMARY KEY (id)
);

ALTER TABLE url_analytics
    ADD CONSTRAINT uc_urlanalytics_short_code UNIQUE (short_code);